GET http://localhost:5134/mygames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InBsYXllcjEiLCJzdWIiOiJwbGF5ZXIxIiwianRpIjoiZWQzZmQ3ZWUiLCJyb2xlIjoicGxheWVyIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6MTI2NTYiLCJodHRwczovL2xvY2FsaG9zdDo0NDM3NyIsImh0dHA6Ly9sb2NhbGhvc3Q6NTEzNCIsImh0dHBzOi8vbG9jYWxob3N0OjcyNTciXSwibmJmIjoxNzEwMjM5MzU1LCJleHAiOjE3MTgxODgxNTUsImlhdCI6MTcxMDIzOTM1NiwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.z-Tno9tEJpSXYvLaPDnwDcjjEFvNqLqeP8WePo5zgqQ


###

GET http://localhost:5134/playergames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InZpdmFrciIsInN1YiI6InZpdmFrciIsImp0aSI6IjE1M2ViMmU2Iiwicm9sZSI6ImFkbWluIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6MTI2NTYiLCJodHRwczovL2xvY2FsaG9zdDo0NDM3NyIsImh0dHA6Ly9sb2NhbGhvc3Q6NTEzNCIsImh0dHBzOi8vbG9jYWxob3N0OjcyNTciXSwibmJmIjoxNzEwMjM0NjIzLCJleHAiOjE3MTgxODM0MjMsImlhdCI6MTcxMDIzNDYyMywiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.0nSmxRUxc1MRIIl05gbC8_9TDTaV_OiKekOYfmJB-68

###

GET http://localhost:5134/mygames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InBsYXllcjEiLCJzdWIiOiJwbGF5ZXIxIiwianRpIjoiM2NkMTUxZDQiLCJyb2xlIjoicGxheWVyIiwic3Vic2NyaXB0aW9uIjoiZ29sZCIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjEyNjU2IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNzciLCJodHRwOi8vbG9jYWxob3N0OjUxMzQiLCJodHRwczovL2xvY2FsaG9zdDo3MjU3Il0sIm5iZiI6MTcxMDI0MDUxOCwiZXhwIjoxNzE4MTg5MzE4LCJpYXQiOjE3MTAyNDA1MTksImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.TESQj_LMvY9v97AQe5R2GS8lFH0k_T6zE-tW412TnJM
