###
GET http://localhost:5134/games

###
GET http://localhost:5134/games/4

###
POST http://localhost:5134/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kids and Family",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5134/games/1
Content-Type: application/json

{
    "id": 1,
    "name": "Street Fighter II Turbo",
    "genre": "Fighting",
    "price": 1009.99,
    "releaseDate": "1992-07-15"
}

###
DELETE http://localhost:5134/games/4
